<a href="https://colab.research.google.com/github/jakeraven/AI-ML/blob/main/Recommendation_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
#loading the data
movies_data = pd.read_csv('movies.csv')
movies_data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [ ]:
#selecting the relevent features
selected_features = ['genres','keywords','tagline','overview','director']
print(selected_features)


['genres', 'keywords', 'tagline', 'overview', 'director']


# New Section

In [ ]:
for feature in selected_features:
  movies_data[feature] = movies_data[feature].fillna('')

In [ ]:
combined_features = movies_data['genres']+''+movies_data['keywords']+''+movies_data['tagline']+''+movies_data['overview']+''+movies_data['director']

In [ ]:
print(combined_features)

0       Action Adventure Fantasy Science Fictioncultur...
1       Adventure Fantasy Actionocean drug abuse exoti...
2       Action Adventure Crimespy based on novel secre...
3       Action Crime Drama Thrillerdc comics crime fig...
4       Action Adventure Science Fictionbased on novel...
                              ...                        
4798    Action Crime Thrillerunited states\u2013mexico...
4799    Comedy RomanceA newlywed couple's honeymoon is...
4800    Comedy Drama Romance TV Moviedate love at firs...
4801    A New Yorker in ShanghaiWhen ambitious New Yor...
4802    Documentaryobsession camcorder crush dream gir...
Length: 4803, dtype: object


In [ ]:
vectorizer = TfidfVectorizer()

In [ ]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [ ]:
print(feature_vectors)

  (0, 4185)	0.17440051790475497
  (0, 15595)	0.12073252500478211
  (0, 5079)	0.18144160644829918
  (0, 1243)	0.1378124467576929
  (0, 1448)	0.05877075491032884
  (0, 22240)	0.1867438381964554
  (0, 1480)	0.034819024003549345
  (0, 20421)	0.17700335595093172
  (0, 11722)	0.15309506679964363
  (0, 3043)	0.10902916673443862
  (0, 28775)	0.1659304567921242
  (0, 2795)	0.10685198806066604
  (0, 4040)	0.06751696703150245
  (0, 18675)	0.12055913312366533
  (0, 29669)	0.16880776076198356
  (0, 20303)	0.053785715822688526
  (0, 18879)	0.17840413117158244
  (0, 28674)	0.03383414241655351
  (0, 8191)	0.19880990606076857
  (0, 15460)	0.045453898645480856
  (0, 17856)	0.15876551710871195
  (0, 20838)	0.22095570437838355
  (0, 4619)	0.13847052991521563
  (0, 259)	0.2148618482308867
  (0, 14864)	0.040313306131134936
  :	:
  (4802, 29208)	0.09081766143024908
  (4802, 28037)	0.0732793167836041
  (4802, 20025)	0.07085204562255099
  (4802, 13210)	0.09025341098108376
  (4802, 30781)	0.08917399164301226
  

In [ ]:
similarity = cosine_similarity(feature_vectors)

In [ ]:
print(similarity)

[[1.         0.061634   0.02726246 ... 0.0330462  0.01588854 0.0092618 ]
 [0.061634   1.         0.05138185 ... 0.05873629 0.04037887 0.02011135]
 [0.02726246 0.05138185 1.         ... 0.03169958 0.0443057  0.0175672 ]
 ...
 [0.0330462  0.05873629 0.03169958 ... 1.         0.0466038  0.02384932]
 [0.01588854 0.04037887 0.0443057  ... 0.0466038  1.         0.03953576]
 [0.0092618  0.02011135 0.0175672  ... 0.02384932 0.03953576 1.        ]]


In [ ]:
print(similarity.shape)

(4803, 4803)


In [ ]:
movie_name = input("Enter Your Favorite Movie Name: ")

Enter Your Favorite Movie Name: x-men


In [ ]:
list_of_all_titles = movies_data['title'].tolist()

In [ ]:
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [ ]:
find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
print(find_close_match)
close_match=find_close_match[0]
print(close_match)

['X-Men', 'Amen.']
X-Men


In [ ]:
index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]
print(index_of_the_movie)

511


In [ ]:
similarity_score = list(enumerate(similarity[index_of_the_movie]))

In [ ]:
print(similarity_score)

[(0, 0.026986258418825966), (1, 0.040055483190852004), (2, 0.054976762853112024), (3, 0.04478267083720178), (4, 0.026540269187725615), (5, 0.008867476010304076), (6, 0.02373894049918675), (7, 0.1761462321658746), (8, 0.029930556497790577), (9, 0.11793460160520672), (10, 0.07647825489639158), (11, 0.04217752188812113), (12, 0.012192906988127597), (13, 0.016428601294345927), (14, 0.1762505280849053), (15, 0.03511945568904602), (16, 0.1847878515871634), (17, 0.02314567237958955), (18, 0.030122748205778784), (19, 0.03982761838736353), (20, 0.0728595136903835), (21, 0.013097760620263556), (22, 0.020648963263362612), (23, 0.016637661210836818), (24, 0.01356026477107651), (25, 0.022787467410019656), (26, 0.0840481841604659), (27, 0.03180880457380894), (28, 0.01641799144012182), (29, 0.035418245594643245), (30, 0.11796172282232945), (31, 0.08583638430669326), (32, 0.018835546526605084), (33, 0.21944876855050682), (34, 0.008413407935914118), (35, 0.024127911748099133), (36, 0.016563350514572202

In [ ]:
sorted_similar = sorted(similarity_score, key= lambda x:x[1], reverse = True)
print(sorted_similar)

[(511, 1.0000000000000002), (64, 0.37195586612937787), (203, 0.3102635006055197), (46, 0.23520777169841617), (33, 0.21944876855050682), (79, 0.21731333208554862), (1720, 0.20253851217544785), (788, 0.18993983180646967), (16, 0.1847878515871634), (174, 0.18468518655637478), (14, 0.1762505280849053), (7, 0.1761462321658746), (126, 0.16185687610983449), (1428, 0.1560749173246742), (182, 0.14917581772209074), (101, 0.14291871380455673), (38, 0.12658918731930063), (4399, 0.12558987882001105), (3981, 0.12095553844005189), (4631, 0.1192332012355629), (30, 0.11796172282232945), (9, 0.11793460160520672), (1740, 0.11740956220139422), (700, 0.11590587558730182), (1024, 0.11550496339604924), (420, 0.1135358030083359), (4033, 0.11289749909487233), (1089, 0.11279154580832162), (870, 0.11129322830049936), (122, 0.11097156148598289), (342, 0.10713395924472723), (241, 0.10648712382474378), (232, 0.10622844125048347), (4440, 0.10348499461118987), (2606, 0.10042294954282734), (4759, 0.09919239614239969),

In [ ]:
print('Movies Suggested for you : \n')
i=1
for movie in sorted_similar:
  index = movie[0]
  title_Suggestion = movies_data[movies_data.index==index]['title'].values[0]
  if (i<20):
    print(i,')',title_Suggestion)
    i=i+1


Movies Suggested for you : 

1 ) X-Men
2 ) X-Men: Apocalypse
3 ) X2
4 ) X-Men: Days of Future Past
5 ) X-Men: The Last Stand
6 ) Iron Man 2
7 ) Kick-Ass
8 ) Deadpool
9 ) The Avengers
10 ) The Incredible Hulk
11 ) Man of Steel
12 ) Avengers: Age of Ultron
13 ) Thor: The Dark World
14 ) Superhero Movie
15 ) Ant-Man
16 ) X-Men: First Class
17 ) The Amazing Spider-Man 2
18 ) Special
19 ) Griff the Invisible


In [ ]:
movie_name = input("Enter Your Favorite Movie Name: ")
list_of_all_titles = movies_data['title'].tolist()
find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
close_match=find_close_match[0]
index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]
similarity_score = list(enumerate(similarity[index_of_the_movie]))
sorted_similar = sorted(similarity_score, key= lambda x:x[1], reverse = True)
print('Movies Suggested for you : \n')
i=1
for movie in sorted_similar:
  index = movie[0]
  title_Suggestion = movies_data[movies_data.index==index]['title'].values[0]
  if (i<20):
    print(i,')',title_Suggestion)
    i=i+1


Enter Your Favorite Movie Name: wolf of the wall street
Movies Suggested for you : 

1 ) The Wolf of Wall Street
2 ) Wall Street
3 ) Shine a Light
4 ) Wall Street: Money Never Sleeps
5 ) The Big Short
6 ) American Psycho
7 ) The Age of Innocence
8 ) Black Nativity
9 ) Mean Streets
10 ) Inside Man
11 ) Buffalo Soldiers
12 ) The Last Waltz
13 ) Taxi Driver
14 ) New York, New York
15 ) Madea's Witness Protection
16 ) Pride and Glory
17 ) She's the One
18 ) Capitalism: A Love Story
19 ) The Town
